import { firstAnswer, secondAnswer } from "./answerer";

describe("Answer 1", () => {
  it("matches the example answer", () => {
    const input = `....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...
`;

    const actual = firstAnswer(input);
    expect(actual).toBe(41);
  });
});

describe("Answer 2", () => {
  it("matches the example answer", () => {
    const input = `....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...
`;

    const actual = secondAnswer(input);
    expect(actual).toBe(6);
  });
});
